import Head from 'next/head'
import Card from '../components/card'

export default function Home() {
  return (
    <div className="bg-[url('/influencer_bg.jpeg')] bg-cover bg-center min-h-screen text-[#1E0536]">
      <Head>
        <title>onlyAuth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-1 gap-6">
          <div className="h-96 py-5 px-20">
            <div className="text-5xl font-bold w-[45%] py-3">Unleash your inner talent and join the community today!</div>
            <div className="grid grid-cols-2 divide-x-0 w-96 py-5">
              <div className="">
                <div>
                  <div className="font-bold text-xl">542</div>
                  <div>Influencers</div>
                </div>
              </div>
              <div className="">
                <div className="font-bold text-xl">321,489</div>
                <div>Total Subscribers</div>
              </div>
            </div>
            <div className="py-5">
                <a href="../create" className="text-white text-md">
                  <button className="rounded-md bg-[#FAAA39] text-[#1E0536] w-80 py-3">Join Us</button>
                </a>
            </div>
          </div>

          <div className="bg-white py-5 px-20 backdrop-filter backdrop-blur-sm bg-opacity-10">
            <span className="text-2xl font-bold">Explore Other Influencers</span>
            <div className="flex space-x-10 py-5">
                <Card status={false}></Card>
                <Card status={true}></Card>
                <Card status={true}></Card>
                <Card status={true}></Card>
            </div>
          </div>
        </div>
      </main>
      <footer>
      </footer>
    </div>
  )
}
